### PR TITLE
Add support for favorite repositories

### PR DESCRIPTION
**Pull request by mads-hartmann**
This PR adds support for marking repositories within "Open Contexts from Github" as favorites. It works the same Raycast Favorite Commands.

Adding to favorites:

Screenshot 2023-11-30 at 22 00 56

If it's the first favorite you can only move it down

Screenshot 2023-11-30 at 21 59 31

if it's the last you can only move it up

Screenshot 2023-11-30 at 21 59 51

Otherwise you can move it up and down

Screenshot 2023-11-30 at 21 59 42

### CODE REVIEW

**Comment by Palanikannan1437** [comment]
Hey @mads-hartmann, thanks for this PR 😀 

Just wanted to know, is this similar to what the "Add to Recents" command does but just in a different section called Favorites?

**Comment by mads-hartmann** [comment]
>Just wanted to know, is this similar to what the "Add to Recents" command does but just in a different section called Favorites?

@Palanikannan1437 "Recents" and "Favorites" serve different purposes. Favorites give you a stable list of repositories that you have full control over. That means it's easier to optimise your key chords for tasks that involve those repositories. E.g. with Favorites I can now hit ^+⌘+G  to open "Open Contexts From Github"  and then ⌘+2 to open the first repository in my Favorites list (if we [remove "Empty Workspace"](https://github.com/gitpod-samples/Gitpod-Raycast-Extension/issues/79) from the list it would be ⌘+1 ). And I know ⌘+<number> will always open the same repository. That's why the re-ordering is quite important, and if we merge this PR I'll implement that next.

I'd like to stay as close as possible to how Raycast handle their list of commands. In that sense "Recents Repositories" and "Recent Contexts" are more like the "Suggestions" section and we could consider merging the two if we wanted. But that's a separate discussion ☺️

**Comment by gtsiolis** [comment]
Thanks, @mads-hartmann and @Palanikannan1437!

The favorites section sounds close to something we were also discussing internally for the desktop app and workspace creation flow, pinned items—sounds great to experiment with this idea in the Raycast extension. 🧪 

| Secret screenshot from design drafts | Secret screenshot from design drafts |
|-|-|
| Screenshot 2023-11-29 at 15 17 04 | Screenshot 2023-11-29 at 15 27 42 |

We should definitely remove the Empty Workspace from there, see https://github.com/gitpod-samples/Gitpod-Raycast-Extension/issues/79—I think it's causing more confusion than help.

> I'd like to stay as close as possible to how Raycast handle their list of commands.

On spot! We should follow any Raycast UX patterns or design guidelines when possible.

_Add to recents_ command makes little sense as that list should autopopulate and not rely on manual addition. Removing an entry from the recents or favorites makes more sense.

**Comment by Palanikannan1437** [comment]
> >Just wanted to know, is this similar to what the "Add to Recents" command does but just in a different section called Favorites?
> 
> @Palanikannan1437 "Recents" and "Favorites" serve different purposes. Favorites give you a stable list of repositories that you have full control over. That means it's easier to optimise your key chords for tasks that involve those repositories. E.g. with Favorites I can now hit ^+⌘+G  to open "Open Contexts From Github"  and then ⌘+2 to open the first repository in my Favorites list (if we [remove "Empty Workspace"](https://github.com/gitpod-samples/Gitpod-Raycast-Extension/issues/79) from the list it would be ⌘+1 ). And I know ⌘+number will always open the same repository. That's why the re-ordering is quite important, and if we merge this PR I'll implement that next.
> 

Thanks for the detailed explanation, cool this makes a lot more sense, we'll consider removing "Add to Recents" then.

My suggestion would be not using cache for this, as Raycast has a ton of optimizations that clears out the cache in a random way, and localstorage would be the best way to go about this from my experience (like I've done for adding branch/pr/issue to Recents)🙌

We could also rename "Add branch to Recents" to "Add branch to Favorites" and show it in a separate section just as you've done with the Repository.

**Comment by mads-hartmann** [comment]
>My suggestion would be not using cache for this, as Raycast has a ton of optimizations that clears out the cache in a random way, and localstorage would be the best way to go about this from my experience (like I've done for adding branch/pr/issue to Recents)🙌

Ah nice, that makes a lot of sense @Palanikannan1437. I've changed it now so that it uses local storage to persist the favorites but still uses the cached state to keep things snappy. Let me know if this matches the best practices for Raycast ☺️

I'm moving this PR back to draft as I want to implement the ability to re-order the list as part of this PR too. Implementing the re-ordering will influence the data we store in the local storage so I'd rather do it as part of this PR so we don't have to deal with potential data migration later ☺️

I'll see if I can find some time today to do this.

> We could also rename "Add branch to Recents" to "Add branch to Favorites" and show it in a separate section just as you've done with the Repository.

Yeah, that sounds good IMO.

**Comment by mads-hartmann** [comment]
@Palanikannan1437 and @gtsiolis I got it to a place where you can reorder the favorites where it takes the various edge-cases into account just like the Raycast command favorites does ☺️ I updated the PR description and put this back into review.

**Comment by mads-hartmann** [comment]
@Palanikannan1437 I extended the PR so that the favourites now respect the search filter too. Is there anything else I can do to help get this merged? I've been using this daily in my own fork for 3 weeks now and having those favourite repositories has been really helpful to my workflows ☺️

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437 I extended the PR so that the favourites now respect the search filter too. Is there anything else I can do to help get this merged? I've been using this daily in my own fork for 3 weeks now and having those favourite repositories has been really helpful to my workflows ☺️

Thank you so so much for this @mads-hartmann, I've pulled this branch and everything looks amazing, I'll use it for say 2-3 days and merge this right in.

PS: Gitpod is such an awesome tool to make apps that need *https* like slack bots/discord.

**Comment by mads-hartmann** [comment]
Happy new years @Palanikannan1437 🥳 Have you had a chance to take the PR for a spin?

**Comment by Palanikannan1437** [comment]
Happy new year to you too @mads-hartmann!! Really appreciate it, thank you so much for this PR, can't wait for #89 to land.

**Comment by mads-hartmann** [comment]
Thanks @Palanikannan1437 - I'll try to make some more progress on #89 next 🚀

**Pull request merged**
