### PR TITLE
Add support for using a monochrome icon for Menu Bar Workspaces

### PR DESCRIPTION
**Pull request by mads-hartmann**
This PR makes it possible to use a monochrome icon for Menu Bar Workspaces. It also uses the monochrome icon as the default to blend in more with the standard MacOS experience.

The color of the menu bar isn't dependent on the System Appearance (light/dark) but rather based on the color of the background. Here's a few screenshots showing how the menu bar icon now works when using a light background in dark/light mode, and a dark background in light/dark mode. Works like a charm.

In a previous attempt (#73) I had used the tint color of Primary Text, but that doesn't work. That's only if you want to use images in the menu bar items, and you want the color to match the color of the text.

Screenshot 2023-11-25 at 18 47 00
Screenshot 2023-11-25 at 18 47 09
Screenshot 2023-11-25 at 18 47 34
Screenshot 2023-11-25 at 18 47 43

### CODE REVIEW

**Comment by Palanikannan1437** [comment]
I suppose this has something to do with the background refresh maybe? What happens if you disable the menubar command and then enable it back again? Does is it work in that case?

**Comment by mads-hartmann** [comment]
@Palanikannan1437 I fixed the issue and have updated the PR description accordingly. It's now ready for review ☺️ @gtsiolis do note that I'm adding even more icons in this PR now, and they might need padding fixes as well 😅

**Comment by Palanikannan1437** [comment]
This looks pretty good to me!! 

Still a bit dicey to keep monochrome as the default 🙈, wdyt @henit-chobisa @mads-hartmann?

**Comment by gtsiolis** [comment]
Adding my vote for **defaulting to the monochromatic version** of the icon, mostly for two reasons:
1. Traditionally, icons in the macOS menu bar are monochromatic, see also [relevant docs](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#:~:text=Consider%20using%20a%20symbol%20to%20represent%20your%20menu%20bar%20extra.).
2. Great tools disappear in use and don't stand in user's face—the colored icon was always in the way when I wanted to use the Raycast extension.

☝️ I'd think this is a two-way door decision we can always change later if needed.

**Comment by mads-hartmann** [comment]
@Palanikannan1437 is there anything I can do to help get this PR in? I'm trying to limit the number of open PRs I have ☺️ I do think defaulting to monochrome makes sense for the same reasons as @gtsiolis outlines above.

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437 is there anything I can do to help get this PR in? I'm trying to limit the number of open PRs I have ☺️ I do think defaulting to monochrome makes sense for the same reasons as @gtsiolis outlines above. 

Hey @mads-hartmann and @gtsiolis, this looks good to me, I'll merge it soon after I update the Readme a bit to tell this is an option, thanks for such detailed feedback and the contribution!!!

**Pull request merged**
