### PR TITLE
[feat] GitHub OAuth added for simpler auth

### LINKED ISSUE #16: Request: Easier link to GitHub Tokens page in auth flow.
The input placeholder for the link to GitHub when setting up the extension means I have to re-write or remember the URL it as there's no easy way to copy paste or click the placeholder text. I would suggest: 

* Make the input placeholder just look like a "real" access token, e.g. `ghp_huMrY****************************`
* Add a clickable link, or some easier flow to get redirected to GitHub for the token

**This is personal preference:** I'd remove the text "Before you can start"... etc, as it's implied by the page. Or, consider shortening the copy to be punchier / quicker? If possible could you put the "about this extension" below the input field, also? Feels like a lot of information that I'm required to read before I input the token? (just some other UI clean up thoughts, a little unrelated to the original issue, but thought I'd share if you make a change to that page 😁 !)

image

### PR DESCRIPTION
**Pull request by Palanikannan1437**
- Closes #16 

Enables a MUCH simpler authentication flow with GitHub OAuth!

gitpod-oauth

### CODE REVIEW

**Comment by filiptronicek** [comment]
@Palanikannan1437 could you please share any instructions for how to best test this? As I have never developed Raycast extensions in the past, I am not sure about the process.

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437 could you please share any instructions for how to best test this? As I have never developed Raycast extensions in the past, I am not sure about the process.

Ohh yeah for sure, you just have to clone it and do `npm i` followed by `npm run dev` just like any other react app 🚀

**Review by filiptronicek — APPROVED** [review]
Awesome stuff, works really really well 🚀 🧡 

My only comment was the weirdly missing GitHub logo, but I assume this is a bug on Raycast's side.

image

**Comment by filiptronicek** [comment]
> Ohh yeah for sure, you just have to clone it and do npm i followed by npm run dev just like any other react app 🚀

Ooo, that's some really nice developer experience right here!

**Comment by Palanikannan1437** [comment]
> > Ohh yeah for sure, you just have to clone it and do npm i followed by npm run dev just like any other react app 🚀
> 
> Ooo, that's some really nice developer experience right here! 
> 
> 
> 
> 

I know right!! From giving react-query level of caching capabilities and configuring commands from within "package.json"...it's really awesome!

Raycast has gone to a level that they've made a custom screenshot tool so that devs can easily create beautiful screeenshots to showcase their app

**Comment by Palanikannan1437** [comment]
> Awesome stuff, works really really well 🚀 🧡
> 
> My only comment was the weirdly missing GitHub logo, but I assume this is a bug on Raycast's side.
> 
> image

A wrong import...fixed it now, not sure how I missed this one 🙈

Thanks for the awesome catch @filiptronicek 🧡

**Pull request merged**
